In [2]:
import pandas as pd
import numpy as np
import csv
import matplotlib.pyplot as plt
%matplotlib inline

from sklearn.linear_model import LinearRegression

In [9]:
accounts = pd.read_csv('dirty_banking_dataset/dirty_accounts.csv')
customers = pd.read_csv('dirty_banking_dataset/dirty_customers.csv')
transactions = pd.read_csv('dirty_banking_dataset/dirty_transactions.csv')
loans = pd.read_csv('dirty_banking_dataset/dirty_loans.csv')

**INSPECT THE DATA**

ACCOUNTS DATA

In [10]:
accounts.head()

,account_id,customer_id,account_type,branch,opening_balance,account_status,open_date
0,1,158,savings,Kisumu,484146.63,NaN,2020-06-22
1,2,352,NaN,Nairobi CBD,166575.93,ACTIVE,2025-08-11
2,3,376,Savings,MOMBASA,510156.57,Active,2024-07-11
3,4,302,CURRENT,NaN,887584.30,NaN,2021-08-26
4,5,161,NaN,MOMBASA,815243.52,Dormant,2025-07-17

In [11]:
accounts.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 710 entries, 0 to 709
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   account_id       710 non-null    int64
 1   customer_id      710 non-null    int64
 2   account_type     588 non-null    object
 3   branch           564 non-null    object
 4   opening_balance  710 non-null    float64
 5   account_status   535 non-null    object
 6   open_date        710 non-null    object
dtypes: float64(1), int64(2), object(4)
memory usage: 39.0+ KB

In [12]:
accounts.isnull().sum()

account_id           0
customer_id          0
account_type       122
branch             146
opening_balance      0
account_status     175
open_date            0
dtype: int64

In [13]:
accounts.duplicated().sum()

np.int64(10)

In [14]:
accounts[accounts.duplicated()]

,account_id,customer_id,account_type,branch,opening_balance,account_status,open_date
700,1,158,savings,Kisumu,484146.63,NaN,2020-06-22
701,2,352,NaN,Nairobi CBD,166575.93,ACTIVE,2025-08-11
702,3,376,Savings,MOMBASA,510156.57,Active,2024-07-11
703,4,302,CURRENT,NaN,887584.30,NaN,2021-08-26
704,5,161,NaN,MOMBASA,815243.52,Dormant,2025-07-17
705,6,518,savings,Kisumu,178321.97,Active,2023-04-12
706,7,362,NaN,Nairobi CBD,690197.85,Active,2022-04-22
707,8,3,CURRENT,NaN,-1067.36,ACTIVE,2023-03-07
708,9,408,Savings,NaN,10518.27,Active,2025-04-08
709,10,202,savings,Kisumu,767811.11,ACTIVE,2021-04-16

In [15]:
accounts.describe()

       account_id  customer_id  opening_balance
count  710.000000   710.000000       710.000000
mean   345.640845   272.315493    499642.338859
std    204.866200   155.839830    291089.841562
min      1.000000     1.000000     -1876.630000
25%    168.250000   140.000000    245544.427500
50%    345.500000   270.000000    510271.330000
75%    522.750000   396.750000    757731.120000
max    700.000000   548.000000    999959.940000

CUSTOMER DATA

In [16]:
customers.head()

,customer_id,first_name,last_name,gender,date_of_birth,email,phone_number,city,occupation,join_date
0,1.0,Gloria,Sims,Female,1985-06-04,patrickbarton@houston-doyle.com,(281)203-8357x7258,nairobi,Teacher,2019-05-19
1,2.0,David,Rodriguez,Male,1983-12-28,mooremadison@gmail.com,+1-638-080-2760x2386,nairobi,ACCOUNTANT,2021-07-05
2,3.0,Robert,Jones,Male,1952-12-21,robertlewis@park-stewart.biz,556.013.2135x0547,nairobi,Engineer,2021-07-24
3,4.0,Paul,Bradley,FEMALE,1980-09-19,joshuashaffer@yahoo.com,001-771-727-5965x9549,Kisumu,Teacher,2025-03-20
4,5.0,Aaron,Garcia,NaN,1970-06-05,townsendjames@williams-becker.com,(178)171-3862x473,Kisumu,ACCOUNTANT,2020-09-20

In [17]:
customers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 515 entries, 0 to 514
Data columns (total 10 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   customer_id    501 non-null    float64
 1   first_name     515 non-null    object
 2   last_name      515 non-null    object
 3   gender         416 non-null    object
 4   date_of_birth  515 non-null    object
 5   email          515 non-null    object
 6   phone_number   515 non-null    object
 7   city           424 non-null    object
 8   occupation     410 non-null    object
 9   join_date      515 non-null    object
dtypes: float64(1), object(9)
memory usage: 40.4+ KB

In [18]:
customers.isnull().sum()

customer_id       14
first_name         0
last_name          0
gender            99
date_of_birth      0
email              0
phone_number       0
city              91
occupation       105
join_date          0
dtype: int64

In [19]:
customers.duplicated().sum()

np.int64(15)

In [20]:
customers[customers.duplicated()]

,customer_id,first_name,last_name,gender,date_of_birth,email,phone_number,city,occupation,join_date
500,1.0,Gloria,Sims,Female,1985-06-04,patrickbarton@houston-doyle.com,(281)203-8357x7258,nairobi,Teacher,2019-05-19
501,2.0,David,Rodriguez,Male,1983-12-28,mooremadison@gmail.com,+1-638-080-2760x2386,nairobi,ACCOUNTANT,2021-07-05
502,3.0,Robert,Jones,Male,1952-12-21,robertlewis@park-stewart.biz,556.013.2135x0547,nairobi,Engineer,2021-07-24
503,4.0,Paul,Bradley,FEMALE,1980-09-19,joshuashaffer@yahoo.com,001-771-727-5965x9549,Kisumu,Teacher,2025-03-20
504,5.0,Aaron,Garcia,NaN,1970-06-05,townsendjames@williams-becker.com,(178)171-3862x473,Kisumu,ACCOUNTANT,2020-09-20
505,6.0,Anthony,Cohen,Female,1973-02-21,levi57@yahoo.com,001-250-729-4212x95184,Nairobi,NaN,2018-12-25
506,7.0,Oscar,Campbell,NaN,2004-11-02,gphillips@yahoo.com,337-359-0197,NAIROBI,ACCOUNTANT,2024-02-27
507,8.0,Kyle,Collins,Female,1981-08-23,duarterachel@byrd-nelson.org,(244)146-6196x620,Kisumu,Engineer,2023-03-25
508,9.0,Sandra,Gardner,NaN,1959-10-11,bill81@gmail.com,(459)456-7941,Kisumu,Teacher,2018-09-12
509,10.0,Dean,Dean,FEMALE,1952-01-08,megansmith@wood.net,001-251-624-1035x440,Mombasa,NaN,2023-09-17
510,11.0,Tami,Thomas,FEMALE,1961-07-23,christopher17@yahoo.com,767.861.4259x01449,Nairobi,Engineer,2021-04-20
511,12.0,Jason,Bailey,Female,1980-05-01,oscarmitchell@hotmail.com,+1-824-945-9480x7074,NAIROBI,ACCOUNTANT,2021-10-12
512,13.0,Stacy,Young,male,1980-08-16,rogersrobert@haynes-landry.com,085-124-9701,NAIROBI,ACCOUNTANT,2022-01-16
513,14.0,Bradley,Thomas,Male,1992-07-18,rebeccamiller@gmail.com,001-173-086-9142x310,Nairobi,NaN,2018-08-03
514,15.0,Becky,Ramirez,FEMALE,1975-05-17,jeffrey86@wood.net,(994)572-9794,NaN,Teacher,2018-08-25

In [21]:
customers.describe()

       customer_id
count   501.000000
mean    244.852295
std     147.992885
min       1.000000
25%     116.000000
50%     246.000000
75%     372.000000
max     500.000000

TRANSACTIONS DATA

In [22]:
transactions.head()

,transaction_id,account_id,customer_id,transaction_type,transaction_amount,transaction_channel,transaction_status,transaction_date
0,1.0,205,247,deposit,2345874.74,NaN,FAILED,2025-08-31 06:42:38
1,2.0,586,334,NaN,3214875.69,NaN,Successful,2025-07-09 22:42:08
2,3.0,126,244,deposit,2191351.07,POS,FAILED,2025-09-26 04:29:16
3,NaN,234,119,Withdrawal,4931673.79,atm,NaN,2024-09-09 19:26:32
4,5.0,602,247,TRANSFER,3161069.27,NaN,FAILED,2024-12-30 17:22:55

In [23]:
transactions.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5020 entries, 0 to 5019
Data columns (total 8 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   transaction_id       4938 non-null   float64
 1   account_id           5020 non-null   int64
 2   customer_id          5020 non-null   int64
 3   transaction_type     4004 non-null   object
 4   transaction_amount   5020 non-null   float64
 5   transaction_channel  3981 non-null   object
 6   transaction_status   3688 non-null   object
 7   transaction_date     5020 non-null   object
dtypes: float64(2), int64(2), object(4)
memory usage: 313.9+ KB

In [24]:
transactions.isnull().sum()

transaction_id           82
account_id                0
customer_id               0
transaction_type       1016
transaction_amount        0
transaction_channel    1039
transaction_status     1332
transaction_date          0
dtype: int64

In [25]:
transactions.duplicated().sum()

np.int64(20)

In [26]:
transactions.describe()

       transaction_id  account_id  customer_id  transaction_amount
count     4938.000000  5020.00000  5020.000000        5.020000e+03
mean      2490.492912   397.60000   301.883267        2.481706e+06
std       1448.248880   230.50192   175.244360        1.451336e+06
min          1.000000     1.00000     1.000000       -1.909211e+04
25%       1235.250000   202.75000   150.000000        1.191916e+06
50%       2489.500000   395.00000   302.000000        2.474744e+06
75%       3745.750000   596.00000   456.000000        3.732338e+06
max       5000.000000   800.00000   600.000000        4.999964e+06

LOANS DATA

In [27]:
loans.head()

,loan_id,customer_id,loan_type,loan_amount,interest_rate,loan_term_months,repayment_status,issue_date
0,1,519,BUSINESS,2431537.13,30.42,NaN,NaN,2024-11-15
1,2,214,Personal,331366.42,6.25,12.0,NaN,2022-01-21
2,3,503,NaN,1480186.97,NaN,NaN,Late,2024-02-07
3,4,102,BUSINESS,484334.97,34.18,48.0,Late,2022-06-02
4,5,527,NaN,568756.18,NaN,12.0,Late,2023-11-08

In [28]:
loans.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 308 entries, 0 to 307
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   loan_id           308 non-null    int64
 1   customer_id       308 non-null    int64
 2   loan_type         222 non-null    object
 3   loan_amount       308 non-null    float64
 4   interest_rate     160 non-null    float64
 5   loan_term_months  249 non-null    float64
 6   repayment_status  227 non-null    object
 7   issue_date        308 non-null    object
dtypes: float64(3), int64(2), object(3)
memory usage: 19.4+ KB

In [29]:
loans.isnull().sum()

loan_id               0
customer_id           0
loan_type            86
loan_amount           0
interest_rate       148
loan_term_months     59
repayment_status     81
issue_date            0
dtype: int64

In [30]:
loans.duplicated().sum()

np.int64(8)

In [31]:
loans.describe()

          loan_id  customer_id   loan_amount  interest_rate  loan_term_months
count  308.000000   308.000000  3.080000e+02     160.000000        249.000000
mean   146.707792   272.487013  1.475457e+06      15.987563         29.590361
std     88.713492   162.471235  8.795566e+05      10.843130         13.544761
min      1.000000     2.000000  9.934590e+03      -1.950000         12.000000
25%     69.750000   129.500000  7.223821e+05       7.155000         12.000000
50%    146.500000   272.000000  1.414387e+06      15.785000         24.000000
75%    223.250000   414.000000  2.253011e+06      25.642500         48.000000
max    300.000000   550.000000  2.999845e+06      34.970000         48.000000

**REMOVE DUPLICATES**

In [32]:
customers = customers.drop_duplicates()
accounts = accounts.drop_duplicates()
transactions = transactions.drop_duplicates()
loans = loans.drop_duplicates()

In [33]:
customers.duplicated().sum()

np.int64(0)

**HANDLE MISSING VALUES**

In [34]:
customers.isnull().sum()

customer_id       14
first_name         0
last_name          0
gender            96
date_of_birth      0
email              0
phone_number       0
city              90
occupation       102
join_date          0
dtype: int64

Fill the missing occupation, gender, and city.

In [35]:
columns_to_fill = ["occupation", "city", "gender"]
customers[columns_to_fill] = customers[columns_to_fill].fillna("Unknown")

In [36]:
customers.head(15)

,customer_id,first_name,last_name,gender,date_of_birth,email,phone_number,city,occupation,join_date
0,1.0,Gloria,Sims,Female,1985-06-04,patrickbarton@houston-doyle.com,(281)203-8357x7258,nairobi,Teacher,2019-05-19
1,2.0,David,Rodriguez,Male,1983-12-28,mooremadison@gmail.com,+1-638-080-2760x2386,nairobi,ACCOUNTANT,2021-07-05
2,3.0,Robert,Jones,Male,1952-12-21,robertlewis@park-stewart.biz,556.013.2135x0547,nairobi,Engineer,2021-07-24
3,4.0,Paul,Bradley,FEMALE,1980-09-19,joshuashaffer@yahoo.com,001-771-727-5965x9549,Kisumu,Teacher,2025-03-20
4,5.0,Aaron,Garcia,Unknown,1970-06-05,townsendjames@williams-becker.com,(178)171-3862x473,Kisumu,ACCOUNTANT,2020-09-20
5,6.0,Anthony,Cohen,Female,1973-02-21,levi57@yahoo.com,001-250-729-4212x95184,Nairobi,Unknown,2018-12-25
6,7.0,Oscar,Campbell,Unknown,2004-11-02,gphillips@yahoo.com,337-359-0197,NAIROBI,ACCOUNTANT,2024-02-27
7,8.0,Kyle,Collins,Female,1981-08-23,duarterachel@byrd-nelson.org,(244)146-6196x620,Kisumu,Engineer,2023-03-25
8,9.0,Sandra,Gardner,Unknown,1959-10-11,bill81@gmail.com,(459)456-7941,Kisumu,Teacher,2018-09-12
9,10.0,Dean,Dean,FEMALE,1952-01-08,megansmith@wood.net,001-251-624-1035x440,Mombasa,Unknown,2023-09-17
10,11.0,Tami,Thomas,FEMALE,1961-07-23,christopher17@yahoo.com,767.861.4259x01449,Nairobi,Engineer,2021-04-20
11,12.0,Jason,Bailey,Female,1980-05-01,oscarmitchell@hotmail.com,+1-824-945-9480x7074,NAIROBI,ACCOUNTANT,2021-10-12
12,13.0,Stacy,Young,male,1980-08-16,rogersrobert@haynes-landry.com,085-124-9701,NAIROBI,ACCOUNTANT,2022-01-16
13,14.0,Bradley,Thomas,Male,1992-07-18,rebeccamiller@gmail.com,001-173-086-9142x310,Nairobi,Unknown,2018-08-03
14,15.0,Becky,Ramirez,FEMALE,1975-05-17,jeffrey86@wood.net,(994)572-9794,Unknown,Teacher,2018-08-25

Customer ID should never be null. The following code drops records with missing critical IDs.

In [37]:
customers = customers.dropna(subset=["customer_id"])

Convert the dates from object to date type

In [38]:
customers["join_date"] = pd.to_datetime(customers["join_date"])
transactions["transaction_date"] = pd.to_datetime(transactions["transaction_date"])

**HANDLE INCONSISTENT FORMATTING**

In [39]:
customers["gender"] =customers["gender"].str.title()
customers["occupation"] =customers["occupation"].str.title()
customers["city"] = customers["city"].str.title()
accounts["branch"] = accounts["branch"].str.title()
accounts["account_type"] = accounts["account_type"].str.title()
accounts["account_status"] = accounts["account_status"].str.title()
loans["loan_type"] = loans["loan_type"].str.title()
transactions["transaction_type"] = transactions["transaction_type"].str.title()
transactions["transaction_status"] = transactions["transaction_status"].str.title()
transactions["transaction_channel"] = transactions["transaction_channel"].str.upper()
customers["email"] = customers["email"].str.strip()

VALIDATE RELATIONSHIPS AND IDs

In [40]:
invalid_transactions = transactions[
    ~transactions["customer_id"].isin(customers["customer_id"])
]

print(invalid_transactions)

      transaction_id  account_id  customer_id transaction_type  \
12              13.0         573          577       Withdrawal
13              14.0         375          545       Withdrawal
17              18.0         509          559         Transfer
21              22.0         632          586          Deposit
22              23.0         373          506         Transfer
...              ...         ...          ...              ...
4983          4984.0         420           58              NaN
4986          4987.0         749          551          Deposit
4992          4993.0         798          517          Deposit
4993          4994.0         375          540          Deposit
4999          5000.0         530          541          Deposit

      transaction_amount transaction_channel transaction_status  \
12            1405604.56                 ATM             Failed
13             670531.36                 ATM             Failed
17            4000296.54                 NaN         Successful
21            3352787.72      MOBILE BANKING         Successful
22            2740156.68                 ATM         Successful
...                  ...                 ...                ...
4983          4379921.40                 ATM         Successful
4986          1025035.06                 NaN             Failed
4992          4882625.93                 NaN                NaN
4993          4492354.28                 NaN         Successful
4999           760794.07                 NaN             Failed

        transaction_date
12   2026-02-12 18:52:59
13   2025-07-11 08:55:32
17   2025-06-28 05:16:50
21   2025-06-29 19:02:26
22   2024-06-10 05:54:26
...                  ...
4983 2024-12-13 23:21:18
4986 2024-09-21 08:09:31
4992 2024-07-31 14:08:17
4993 2025-12-05 03:35:41
4999 2024-09-19 10:24:28

[983 rows x 8 columns]

**HANDLE OUTLIERS**
Remove negative transactions

In [41]:
transactions = transactions[
    transactions["transaction_amount"] > 0
]

In [42]:
transactions.describe()

,transaction_id,account_id,customer_id,transaction_amount,transaction_date
count,4905.000000,4987.000000,4987.000000,4.987000e+03,4987
mean,2500.670133,397.419892,302.064568,2.490465e+06,2025-05-13 16:03:19.404652032
min,1.000000,1.000000,1.000000,4.520100e+02,2024-05-11 05:49:40
25%,1252.000000,202.000000,150.000000,1.212021e+06,2024-11-11 09:03:43
50%,2499.000000,394.000000,302.000000,2.479334e+06,2025-05-18 20:48:32
75%,3751.000000,596.000000,456.000000,3.738436e+06,2025-11-14 18:18:30
max,5000.000000,800.000000,600.000000,4.999964e+06,2026-05-11 05:57:37
std,1442.810752,230.472696,175.139771,1.448334e+06,NaN

**DETECT ANOMALIES**

In [43]:
threshold = transactions["transaction_amount"].quantile(0.99)

anomalies = transactions[
    transactions["transaction_amount"] > threshold
]

**DERIVE COLUMNS**:
Customer Age

In [44]:
today = pd.Timestamp.today()
customers["age"] = (
    today.year - pd.to_datetime(customers["date_of_birth"]).dt.year
)

In [45]:
customers.head()

,customer_id,first_name,last_name,gender,date_of_birth,email,phone_number,city,occupation,join_date,age
0,1.0,Gloria,Sims,Female,1985-06-04,patrickbarton@houston-doyle.com,(281)203-8357x7258,Nairobi,Teacher,2019-05-19,41
1,2.0,David,Rodriguez,Male,1983-12-28,mooremadison@gmail.com,+1-638-080-2760x2386,Nairobi,Accountant,2021-07-05,43
2,3.0,Robert,Jones,Male,1952-12-21,robertlewis@park-stewart.biz,556.013.2135x0547,Nairobi,Engineer,2021-07-24,74
3,4.0,Paul,Bradley,Female,1980-09-19,joshuashaffer@yahoo.com,001-771-727-5965x9549,Kisumu,Teacher,2025-03-20,46
4,5.0,Aaron,Garcia,Unknown,1970-06-05,townsendjames@williams-becker.com,(178)171-3862x473,Kisumu,Accountant,2020-09-20,56

**DATA QUALITY CHECKS**
- The following codes check whether the customer IDs are nique and that there are no missing values in the transaction_amount column. An AssertionError arise if the mentioned criteria are not met.

In [46]:
assert customers["customer_id"].is_unique

In [47]:
assert transactions["transaction_amount"].isnull().sum() == 0

**SAVE CLEANED DATA**

In [48]:
customers.to_csv("clean_customers.csv", index=False)
transactions.to_csv("clean_transactions.csv", index=False)
accounts.to_csv("clean_accounts.csv", index=False)
loans.to_csv("clean_loans.csv", index=False)