In [20]:
%pip install pandas sqlalchemy psycopg2-binary

Requirement already satisfied: pandas in c:\users\klynn\anaconda3\lib\site-packages (2.3.3)
Requirement already satisfied: sqlalchemy in c:\users\klynn\anaconda3\lib\site-packages (2.0.43)
Requirement already satisfied: psycopg2-binary in c:\users\klynn\anaconda3\lib\site-packages (2.9.12)
Requirement already satisfied: numpy>=1.26.0 in c:\users\klynn\anaconda3\lib\site-packages (from pandas) (2.3.5)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\klynn\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\klynn\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\klynn\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: greenlet>=1 in c:\users\klynn\anaconda3\lib\site-packages (from sqlalchemy) (3.2.4)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\klynn\anaconda3\lib\site-packages (from sqlalchemy) (4.15.0)
Requirement already satisfied: six>=1.5 in c:\users\klynn\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [21]:
from sqlalchemy import create_engine

In [40]:
engine = create_engine(
    "postgresql+psycopg2://postgres:mypassword@localhost:5432/Banking_project"
)

In [53]:
dim_customers = pd.read_csv("Downloads/clean_customers.csv")
fact_transactions = pd.read_csv("Downloads/clean_transactions.csv")
dim_accounts = pd.read_csv("Downloads/clean_accounts.csv")
fact_loans = pd.read_csv("Downloads/clean_loans.csv")

In [54]:
customers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 486 entries, 0 to 485
Data columns (total 11 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   customer_id    486 non-null    float64
 1   first_name     486 non-null    object
 2   last_name      486 non-null    object
 3   gender         486 non-null    object
 4   date_of_birth  486 non-null    object
 5   email          486 non-null    object
 6   phone_number   486 non-null    object
 7   city           486 non-null    object
 8   occupation     486 non-null    object
 9   join_date      486 non-null    object
 10  age            486 non-null    int64
dtypes: float64(1), int64(1), object(9)
memory usage: 41.9+ KB

In [55]:
engine.connect()

In [56]:
dim_customers.to_sql(
    "dim_customers",
    engine,
    if_exists="replace",
    index=False
)
print ("Customers table loaded successfuly")

Customers table loaded successfuly

In [57]:

fact_transactions.to_sql(
    "fact_transactions",
    engine,
    if_exists="replace",
    index=False
)
print("Transactions table loaded successfuly")

Transactions table loaded successfuly

In [59]:
fact_loans.to_sql(
    "fact_loans",
    engine,
    if_exists="replace",
    index=False
)
print("Loans table loaded successfuly")

Loans table loaded successfuly

In [60]:
dim_accounts.to_sql(
    "dim_accounts",
    engine,
    if_exists="replace",
    index=False
)
print("Accounts table loaded successfuly")

Accounts table loaded successfuly

In [51]:
transactions.head()

,transaction_id,account_id,customer_id,transaction_type,transaction_amount,transaction_channel,transaction_status,transaction_date
0,1.0,205,247,Deposit,2345874.74,NaN,Failed,2025-08-31 06:42:38
1,2.0,586,334,NaN,3214875.69,NaN,Successful,2025-07-09 22:42:08
2,3.0,126,244,Deposit,2191351.07,POS,Failed,2025-09-26 04:29:16
3,NaN,234,119,Withdrawal,4931673.79,ATM,NaN,2024-09-09 19:26:32
4,5.0,602,247,Transfer,3161069.27,NaN,Failed,2024-12-30 17:22:55

In [61]:
dim_accounts.describe()

       account_id  customer_id  opening_balance
count   700.00000   700.000000       700.000000
mean    350.50000   272.145714    500337.959714
std     202.21688   156.000904    290559.018809
min       1.00000     1.000000     -1876.630000
25%     175.75000   139.000000    248729.287500
50%     350.50000   270.000000    510588.185000
75%     525.25000   397.500000    756485.460000
max     700.00000   548.000000    999959.940000